- docs/03-getting-started/01-setup.mdx
> chore:  update setup commands

- docs/03-getting-started/03-example-app.mdx
> update(docs): update docs for context creation

- docs/03-getting-started/03-setup-your-first-context/02-invite-to-context.mdx
invitation doc had some formatting issues
> chore(docs): fix invitation doc

- docs/04-build/04-dev-mode.mdx
Added part of dev mode documentation to show potential users that using the cli is safe and protected by the nodes private key.
> Added sentence to show that the communication is being protected

- docusaurus.config.ts
- src/pages/index.tsx
* Remove mentions to Calimero 2.0
* Fix title:
Docusaurus interpolates the title in the config with the title passed in the component.
* Replace hardcoded description with tagline text
> fix: update title and minor tweaks

- docs/07-integrations/02-blockchains/01-near-integration.mdx
Updated NEAR Integration documentation, describing the login process and configuration contract
> feat: updated NEAR integration documentation

- docs/03-getting-started/01-setup.mdx
- docs/04-build/04-dev-mode.mdx
update of docs after: https://github.com/calimero-network/core/pull/796/files
> update docs after node/cli split

- docs/07-integrations/02-blockchains/02-starknet-integration.mdx
This PR adds documentation for the Starknet integration, focusing on the login process with ArgentX and Metamask Snap wallets. 
The documentation outlines the step-by-step login flow and provides a detailed explanation of the signature verification process for each wallet type, highlighting Calimero's secure authentication mechanism for Starknet users.
> feat: Updated Starknet integration docs with login process

- docs/07-integrations/02-blockchains/03-icp-integration.mdx
This PR updates the ICP integration documentation with the explanation of the login process for users using Internet Identity.
It provides an overview of the authentication flow using Internet Identity, highlights the current scope of the integration, and outlines future development plans.
> feat: updated ICP documentation with login process

- docs/03-getting-started/03-setup-your-first-context/02-invite-to-context.mdx
`identity` command is extracted from the `context`
> chore: update identity command

- docs/04-build/02-client-sdks/02-client-ts-sdk.mdx
- docusaurus.config.ts
- package.json
- pnpm-lock.yaml
> added the edit button to make contributions easier

- docs/04-build/05-tests.mdx
Update command for running tests
> chore: update tests

- docs/04-build/05-tests.mdx
Reverts calimero-network/calimero-network.github.io#48
> Revert "chore: update tests"

- docusaurus.config.ts
Reverts calimero-network/calimero-network.github.io#64
> revert "chore: add analytics"

- docs/02-getting-started/01-setup.mdx
- docs/05-developer-tools/02-SDK/03-protocol-sdk/02-protocol-rs-sdk.mdx
- Use `UnorderedMap`
- Remove `Element`
- Expand on error handling documentation
> docs: revise rust protocol sdk docs

- docs/05-developer-tools/01-CLI/02-meroctl.mdx
- versioned_docs/version-0.3.0/05-developer-tools/01-CLI/02-meroctl.mdx
> chore: document new meroctl changes in context {contextId} get

- .github/workflows/style.yml
- package.json
> chore: add style workflow

- docs/05-developer-tools/01-CLI/02-meroctl.mdx
- docs/06-tutorials/02-create-context.mdx
- docs/06-tutorials/03-invitations-and-joinings.mdx
- docs/shared/context-create-binary.mdx
> feat(docs): add alias docs

- docs/05-developer-tools/01-CLI/02-meroctl.mdx
- docs/05-developer-tools/02-SDK/04-client-sdk/calimero-client-js.mdx
- docs/06-tutorials/03-invitations-and-joinings.mdx
- docs/06-tutorials/07-awesome-projects/03-building-with-icp.mdx
- docs/06-tutorials/07-awesome-projects/04-building-with-stellar.mdx
- versioned_docs/version-0.2.0/03-getting-started/03-setup-your-first-context/02-invite-to-context.mdx
- versioned_docs/version-0.3.0/06-tutorials/03-invitations-and-joinings.mdx
- versioned_docs/version-0.3.0/06-tutorials/07-awesome-projects/03-building-with-icp.mdx
Changes regarding this PR:
https://github.com/calimero-network/core/pull/1114
> patch(docs): cli API changes

- docs/06-tutorials/07-awesome-projects/05-building-with-ethereum.mdx
- i18n/en/docusaurus-plugin-content-docs/version-0.5.0.json
- versioned_docs/version-0.5.0/06-tutorials/07-awesome-projects/05-building-with-ethereum.mdx
Code style failing in new PR's as this updates were not pushed. 
Deployed version - Local with proper parsing (no visual changes)
> fix: code style + lint

- docs/06-tutorials/03-invitations-and-joinings.mdx
- versioned_docs/version-0.5.0/05-developer-tools/01-CLI/01-merod.mdx
> fix: cli commands fix

- docs/06-tutorials/03-invitations-and-joinings.mdx
As some of the commands were updated, also updating the tutorial commands.
> feat: update invitation commands

- docs/04-architecture/03-node/03-server.mdx
- docs/05-developer-tools/04-admin-api.mdx
This PR adds comprehensive documentation for the Calimero Admin API, addressing the need for developers to understand request/response formats without trial-and-error.
- **Complete API Reference**: Documents all 50+ admin API endpoints with full request/response schemas
- **Practical Examples**: Real curl commands and JSON examples for immediate use
- **Workflow Guides**: Step-by-step examples for common operations (create context, invite users, etc.)
- **Error Handling**: HTTP status codes, error responses, and troubleshooting guidance
- **Integration Ready**: Authentication, rate limiting, and WebSocket support information
- Health checks & authentication
- Application management (install, list, uninstall)
- Context management (create, delete, invite, join, sync)
- Identity management & …
> Add comprehensive Admin API documentation with 50+ endpoints, schemas, and examples

- docs/05-developer-tools/02-SDK/04-client-sdk/calimero-client-py.mdx
- docs/06-tutorials/08-python-client-integration.mdx
- docusaurus.config.ts
- i18n/en/docusaurus-plugin-content-docs/current.json
- pnpm-lock.yaml
- static/llms.txt
1. Clean up build warnings
2. Update llms.txt (what we get from the plugin itself is still not ideal, but the patched version was improved)
3. Python client docs improved with more testing
> chore: improve py client docs, other TLC
